gh_url: https://github.com/nottyo
browser: chrome
account_name: nottyo
explicit_timeout: 10s

#api
gh_api: https://api.github.com
get_users: /users

#chrome_options
chrome_options:
  - --headless
  - --disable-gpu